#include <stdio.h>
#include <stdlib.h>
#pragma warning (disable: 4996) // required to suppress deprecated method call warning

// Defined constant
#define CAPACITY              10
#define FIRST_CLASS_SEAT_TYPE 1
#define ECONOMY_SEAT_TYPE     2

// Memory constant
const int FIRST_CLASS_SEAT_NO_FROM = 1;
const int FIRST_CLASS_SEAT_NO_TO   = 5;
const int ECONOMY_SEAT_NO_FROM     = 6;
const int ECONOMY_SEAT_NO_TO       = 10;

// Function declaration (prototype)
void displayWelcomeScreen();
void displayExitScreen();
void printBordingPass(int assignedSeatNo);
int  isValidSeatType(int selection);
int  isEmptySeat(int occupancy);

void main()
{
    // Variable initializations
    int seatPlan[CAPACITY] = { 0 },
        totalAssignedSeats = 0;

    // Variable declaration
    int seatNoFrom, seatNoTo, isSeatAssignSuccessful, assignedSeatNo;

    // Variable declaration (user input)
    int  seatType;
    char switchSeatType;

    do
    {
        isSeatAssignSuccessful = 0;

        do
        {
            displayWelcomeScreen();
            scanf("%d", &seatType);

            if (!isValidSeatType(seatType))
            {
                puts("\nInvalid selection! Please enter 1 or 2 only.\n");

                system("pause");
                system("cls");
            }
        } while (!isValidSeatType(seatType));

        if (seatType == FIRST_CLASS_SEAT_TYPE)
            puts("Assigning \"first class\" seat...");
        else
            puts("Assigning \"economy\" seat...");

        if (seatType == FIRST_CLASS_SEAT_TYPE)
        {
            seatNoFrom = FIRST_CLASS_SEAT_NO_FROM;
            seatNoTo   = FIRST_CLASS_SEAT_NO_TO;
        }
        else
        {
            seatNoFrom = ECONOMY_SEAT_NO_FROM;
            seatNoTo   = ECONOMY_SEAT_NO_TO;
        }

        for (int i = seatNoFrom - 1; i <= seatNoTo - 1; i++) // NOTE: array index is 0-based
        {
            if (isEmptySeat(seatPlan[i]))
            {
                isSeatAssignSuccessful = 1;

                totalAssignedSeats++;
                seatPlan[i]    = 1;
                assignedSeatNo = i + 1;

                printBordingPass(assignedSeatNo);
                break;
            }
        }

        if (isSeatAssignSuccessful == 0) // If exisiting seat type is unavailable, request for another seat type
        {
            rewind(stdin); // clear input buffer to remove the line feed (LF) character generated by the "Enter" key

            printf(
                "Unfortunately the corresponding seat type has been fully booked.\n"
                "Would you mind to switch to another seat type?\n"
                "Press Y to proceed or any other key to cancel. ");
            scanf("%c", &switchSeatType);
            //switchSeatType = getchar(); // alternative

            puts("");

            if (switchSeatType == 'y' || switchSeatType == 'Y')
            {
                if (seatType == FIRST_CLASS_SEAT_TYPE)
                {
                    seatNoFrom = ECONOMY_SEAT_NO_FROM;
                    seatNoTo   = ECONOMY_SEAT_NO_TO;
                }
                else
                {
                    seatNoFrom = FIRST_CLASS_SEAT_NO_FROM;
                    seatNoTo   = FIRST_CLASS_SEAT_NO_TO;
                }

                for (int i = seatNoFrom - 1; i <= seatNoTo - 1; i++) // NOTE: array index is 0-based
                {
                    if (isEmptySeat(seatPlan[i]))
                    {
                        totalAssignedSeats++;
                        seatPlan[i]    = 1;
                        assignedSeatNo = i + 1;

                        printBordingPass(assignedSeatNo);
                        break;
                    }
                }
            }
            else
            {
                puts("Next flight leaves in 3 hours.");
            }
        }

        system("pause");
        system("cls"); // clear console screen
    } while (totalAssignedSeats < 10);

    displayExitScreen();

    puts("\n");
    system("pause");
}

void displayWelcomeScreen()
{
    puts("+~.~.~.~.~.~.~.~.~.~.~.~.~.~.~.~.~.~.~.~.~.~.~.~+");
    puts("| WELCOME TO FLYHIGH AIRLINE RESERVATION SYSTEM |");
    puts("+~.~.~.~.~.~.~.~.~.~.~.~.~.~.~.~.~.~.~.~.~.~.~.~+\n");

    puts("Please type 1 for \"first class\"");
    puts("Please type 2 for \"economy\"\n");
    printf("Your choice : ");
}

void displayExitScreen()
{
    puts("+~.~.~.~.~.~.~.~.~.~.~.~.~.~.~.~.~.~.~.~.~.~.~.~.~.~.~.~.~+");
    puts("* THANK YOU FOR USING FLYHIGH AIRLINE RESERVATION SYSTEM! |");
    puts("+~.~.~.~.~.~.~.~.~.~.~.~.~.~.~.~.~.~.~.~.~.~.~.~.~.~.~.~.~+");
}

void printBordingPass(int assignedSeatNo)
{
    puts("Successful! Printing bording pass...\n");
    printf("+-----------------------------------+----------+\n");
    printf("| FLYHIGH AIRLINE                   | Seat No. |\n");
    printf("|                                   |          |\n");
    printf("| Depature Date : 25 October 2017   |    %2d    |\n", assignedSeatNo);

    if (assignedSeatNo >= FIRST_CLASS_SEAT_NO_FROM &&
        assignedSeatNo <= FIRST_CLASS_SEAT_NO_TO)
        printf("| Section       : %-17s |          |\n", "First class");
    else
        printf("| Section       : %-17s |          |\n", "Economy");

    printf("+-----------------------------------+----------+\n");
}

int isValidSeatType(int type)
{
    return type == FIRST_CLASS_SEAT_TYPE || type == ECONOMY_SEAT_TYPE;
}

int isEmptySeat(int occupancy)
{
    return occupancy == 0;
}
